name: Tar templates and upload

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/templates.yaml"
      - ".github/workflows/scripts/tar_files.sh"
      - "templates/**/*"

env:
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  tar-files:
    name: Tar templates and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Tar files
        run: |
          .github/workflows/scripts/tar_files.sh

      - name: Deploy tar files
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: output
