name: Tar templates and upload

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/templates.yaml"
      - "templates/**/*"

env:
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  tar-files:
    name: Tar templates and upload
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dir: ./templates/kubernetes
            name: kubernetes
    steps:
      - uses: actions/checkout@v2

      - name: Tar files
        run: |
          mkdir -p outputs/
          tar -czvf outputs/${{ matrix.name }}.tar.gz ${{ matrix.dir }}

  upload-tar-files:
    name: Upload tar files
    runs-on: ubuntu-latest
    needs: tar-files
    steps:
      - uses: actions/checkout@v2

      - name: Deploy tar files
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: docs/pipelines
